### ISSUE TITLE
Can we add numbers arround 

### ISSUE THREAD

**Issue by ineffablep** [princejwesley/angular-circular-slider#1]
Hi
Can we add numbers around this 0 to 60, so user can drag from 0 to 45 value

**Comment by princejwesley** [comment]
Hi

This plugin is in development. Need some tweak to make it work in angular way.

At the moment, you can use something like this:

``` html
    <circular-slider class='my-slider' shape='Circle' value='0' selectable='false' touch="true" animate='true'>
      <!-- $parent.value hold sliding value-->
      <div>
        {{$parent.value}}
      </div>
    </circular-slider>
```

Or wrap this [jQuery](https://github.com/princejwesley/circular-slider) version in directive(if you have jQuery dependency).

Once this tool is ready, we will be having a `slider` binding inside the directive to access slider functions inside the directive elements instead of accessing from `$parent`.
